
title: My Personal Web Page
url: 'https://bugcegokce.github.io/'
baseurl: '/bugcegokce' #change it according to your repository name



# Profile information
yourname: Buğçe GÖKÇE  ## put your name
title: 'Geomatik Mühendisi'  ## your title
location: Ankara , TR


## Social Profiles
facebook: https://www.facebook.com/bugce.gokce  ## your facebook account url
linkedin: https://www.linkedin.com/in/bu%C4%9F%C3%A7e-g%C3%B6k%C3%A7e-41068011a/  ## your linkedin account url
instagram: https://www.instagram.com/bgcgkc



# Update all the sections by editing the files inside _includes folder.
